# Generated by Django 6.0.3 on 2026-03-19 09:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20, unique=True, verbose_name='Date')),
                ('foundation_year', models.CharField(max_length=30, unique=True, verbose_name='Foundation generation')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Is Digital Network')),
                ('system_status', models.CharField(default='OFFLINE', max_length=50, verbose_name='Current Status')),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            managers=[
                ('generations', django.db.models.manager.Manager()),
            ],
        ),
    ]
